### ISSUE TITLE
I'd like to use a game score history api.

### ISSUE THREAD

**Issue by cksdlakstp12** [Nexure/DBD-API#11]
I'd like to use a game score or history api.

Hello. I want to search my entire game score or history while playing dead by daylight, but I don't have any related sites. So I want to make it myself. If you don't mind, could you tell me if there is an api related to the game score or history? If you have, could you get the api? I'm a beginner in development, so I can't create api, so please get that api.

**Comment by Nexure** [comment]
Ah, sorry but I have not come across any game history API's and most of the reported player stats we get are mainly from the Steam API.
