### ISSUE TITLE
Data inconsistency

### ISSUE THREAD

**Issue by tmhharvey** [Nexure/DBD-API#12]
Awesome and easy to use API man!  I've been messing with it a bit on a personal project just for fun.  Unfortunately a lot of the data seems a bit inconsistent, I'm assuming that's on DBD's end though?

**Comment by jesterret** [comment]
Can You give example of which endpoint You mean?  
If I'm not mistaken, endpoints 1-12 (per Readme, maybe with exception of #8?) are dumps of deserialized data from the game files.

**Comment by tmhharvey** [comment]
Yeah no problem! For example, in endpoint no. 2 perks have 'tags' on them which usually references the owner of the perk's name. I wanted to pull all the perks belonging to killers and then display the killer's name associated with the perk using the 'tags' property but some of the tags don't have anything in them (for example Barbecue and Chili).

**Comment by jesterret** [comment]
Yeah, that's how the game has it. You can always shout at devs to be more consistent in their data :D

For that use case, it would be more reliable to use 'AssociatedPlayerIndex', which is index of killer/survivor, where `index & 0xF0000000` being set means it's killer character, and they're all incremented from 1 by release order (survivors and killers incremented separately).

**Comment by tmhharvey** [comment]
Ahh okay, awesome! Thanks for the info, I didn't see that connection haha.  And yeah, I figured it was on the Dbd dev's end, darn them :P
