### ISSUE TITLE
shrine/storeoutfits DBD endpoint changed

### ISSUE THREAD

**Issue by AxonneQ** [Nexure/DBD-API#15]
Hey Nexure, I tried adding you on steam/discord weeks ago but I guess you haven't seen those invites. 

Anyways I think that the dbd backend address for guest logins/shrine/outfits changed from
`latest.live.dbd.bhvronline.com` to `steam.live.bhvrdbd.com`. However I am not able to get shrine from those endpoints. (I wasn't able to before the change either). After logging in as guest, I get a response from shrine endpoint: "Unable to find requested data in shrine market catalog".

Outfits work, however they are outdated, only 407 entries are shown. I can't for the life of me figure out how to solve this. I tried contacting the creator of dbd leaderboards website on his discord but he just deleted my message. 

Hope you have some time to look into it as you have way more knowledge than me in this regard. Thanks!

**Comment by Nexure** [comment]
Heyyo, I've gone ahead and changed the endpoints, I'm currently fixing more stuff. I may release the update soon!

**Comment by AxonneQ** [comment]
I see, good to hear you still work on this project. Hopefully that will answer some questions once you update it. I am basing a very simplified node server on this, and can't get shrine to work :)

**Comment by Nexure** [comment]
Yeah, its been sometime since I've worked on it. Also gonna fix some issues with it not getting the latest DLC (its probably located in another PAK file)

**Comment by Nexure** [comment]
Fixes have been pushed, and this issue is solved.
