### ISSUE TITLE
DbD source API?

### ISSUE THREAD

**Issue by newshamu** [Nexure/DBD-API#32]
I am impressed with this project and am looking forward to seeing it more fleshed out. I have wanted to do something like this for a while myself, but never found a way to access a DbD API, at least not an official one from Behaviour. Where are you getting the info that you are hosting/displaying? Is there a Behaviour-hosted API that you are tapping into? I couldn't find it in your source code.

**Comment by OutOfBears** [comment]
Hello! I'm glad you have taken an interest in the project :). We do indeed use the an API from Behavior, you can see such interactions [here](https://github.com/Nexure/DBD-API/blob/master/DBD-API/Services/DdbService.cs#L284). We also use steam to grab metadata from user, and display it back. Then for the rest of the actual data, for example maps, addons, etc, we read it from the PAK files, which are downloaded with the game.
