### ISSUE TITLE
List of lobbies

### ISSUE THREAD

**Issue by Oryteclin** [Nexure/DBD-API#4]
What API should I use to get the list of active lobbies from the game?
Is it */api/v1/queue or */api/v1/gameon?

**Comment by Nexure** [comment]
I haven't figured that out, though I know they use some sort of polling and generate a random GUID for each lobby. When I get back from my vacation, I'll see if I can look into it a bit more.

**Comment by Nexure** [comment]
When checking these api's, one of them doesn't exist (gameon), and queue is what DBD uses to make you queue into a lobby, not query a list of lobbies. May figure out in the future™️ .
