### ISSUE TITLE
Invalid response from DBD CDN on dev branch

### ISSUE THREAD

**Issue by wladimiiir** [Nexure/DBD-API#6]
When trying to access https://dbd.wolfer.io/api/archive?branch=dev the following error is shown

Invalid response from DBD CDN

There seems to be problem with Access Denied when accessing the branch, I guess some specific authentication is needed for the branch. Is it possible to implement it such authentication for dev branch on your side?

PS: Thanks for your great work.

**Comment by Nexure** [comment]
Hello! Sorry for the long response, I'll start debugging the API and see why its returning an invalid response. Maybe the devs changed part of their api/cdn to require authentication.

**Comment by Nexure** [comment]
After checking with some people, it seems they protected the endpoint with some credentials we dont have. So saddly we cannot make it grab the dev branch of the archives. Sorry, if someone tells us how I can add it to the website, but until then I guess it'll have to stay the way it is. :(
