### ISSUE TITLE
Game Data available through the API

### ISSUE THREAD

**Issue by Rekenna** [Nexure/DBD-API#7]
Hey Nexure!

Stumbled on your API this afternoon and I really like it! I was curious to see if you have any plans to add game data to any of the endpoints?

For example:
- `/api/killers` to get a list of the killers with related information/specific perks
- `/api/survivors` to get a list of the survivors with related information/specific perks
- `/api/perks` to get a list of all of the perks available in the game (maybe this should be divided into two separate endpoints, one for killer perks and one for survivor perks)
- `/api/items`
- `/api/offerrings`

**Comment by Nexure** [comment]
Hello!

Yes, I can implement those into the API, which I do have mostly planned todo, to help the perk names. But this requires me downloading the PAK file from steam, and extracting it (which is what hold all of such information). Though there are open source tools to do so, I've just gotta go ahead and implement them.

**Comment by jesterret** [comment]
Just FYI, actual data & numbers are serialized in ue4 binary format, so extracting PAK's won't help too much.

**Comment by Nexure** [comment]
Progress is being made [in this repo](https://github.com/Nexure/UE4-Inspector) to be able to read some perk info, etc and make it available through the API. Also implement a downloader from the API to automatically download the PAK files from steam.

**Comment by jesterret** [comment]
If You want I could hit You up with newer version of the library (part of why I abandoned that project for now, expanded it a lot, it's in almost release ready state) in about a week ;)

**Comment by Nexure** [comment]
Yeah sure! :) That'd be great been having an issue or two with the current one.

**Comment by jesterret** [comment]
Hi, You can find the libs [here](https://github.com/UnrealTools/UnrealTools), might not be the most intuitive setup right now, so let me know if You have any questions, suggestions etc :)
P.S.
Sorry they're in .netcore3.0, didn't have time to deal with backporting conflicts to netstandard2.0 properly yet, might do it over the weekend.

**Comment by Nexure** [comment]
Thank you! just pushed a commit to move over to .net core 3.0, now just gotta fix some bugs and read the pak file.

**Comment by Nexure** [comment]
The endpoints for such information has been implemented, read the README for the endpoints to get the info.

**Comment by Rekenna** [comment]
@Nexure Sweet! Looks like the `?branch=live` part isn't up yet. Is there another branch I should be using?
