### ISSUE TITLE
question

### ISSUE THREAD

**Issue by PE4EHbKA-web** [Nexure/DBD-API#8]
Hello,can u help me please?How can I get data about DBD users?After I try to send a GET request I get a 404 error 
![image](https://user-images.githubusercontent.com/61183882/74721212-1617c180-5248-11ea-9770-72c5e386c439.png)

**Comment by jesterret** [comment]
As the error response says, this api endpoint doesn't exist.

**Comment by PE4EHbKA-web** [comment]
> As the error response says, this api endpoint doesn't exist.

But how i can get data player?

**Comment by jesterret** [comment]
https://github.com/Nexure/DBD-API/blob/775b8f309fc2641017c9ef2ec33d39bad723198f/DBD-API/Services/SteamService.cs#L129
Trace how it's getting data here.

**Comment by Nexure** [comment]
Hello! Sorry for the late response, but it seems your using the wrong endpoint, your using DBD's endpoint to get player stats which does not exist. You can use the one built into the API:
https://dbd-stats.info/api/stats/76561198807823607

**Comment by PE4EHbKA-web** [comment]
> Hello! Sorry for the late response, but it seems your using the wrong endpoint, your using DBD's endpoint to get player stats which does not exist. You can use the one built into the API:
> https://dbd-stats.info/api/stats/76561198807823607

But how can I get data from other APIs? I mean /api/config,bpevents and etc.

**Comment by jesterret** [comment]
Oh, I seem to have misunderstood Your intentions, and @Nexure got it right.
Basically, all the endpoints listed in readme are relative to his domain, so
https://dbd-stats.info + whatever endpoint You need.
so for Your example:
https://dbd-stats.info/api/config
https://dbd-stats.info/api/bpevents
