### ISSUE TITLE
Pictures of the characters and their perks 

### ISSUE THREAD

**Issue by MohamadAlGhorani** [Nexure/DBD-API#9]
Nice work thank you very much for this api but i have a question about the images of the characters. 
1- Can you tell me how can i get the picture of each character from the api?
2- Is this api up to date?
3- if there is a new characters in the game can i find those new characters in the data? 

iconPath: "UI/Icons/CharPortraits/DF_charSelect_portrait.png"
backgroundPath: "UI/Icons/StoreBackgrounds/storeBackground_DF.png"
this is what i see and i get nothing back 
thanks

**Comment by jesterret** [comment]
Hi,
1 - the paths You see are raw extracts from the game files, relative to dbd instalation directory. It's not documented/official way, but I see the pictures on site keep the dbd format for pictures too, so just append path to `https://dbd-stats.info/data/Public/` and unless @Nexure changes something, or wants to introduce other api, it should be good.
2 - As far as I know, yeah. Obviously character data is using live servers, not ptb tho.
3 - Yes, within reason, when the new character comes out the backend has to download the changed files too ;)
